#!/bin/sh
set -eu

lb config noauto \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free-firmware" \
  --debian-installer none \
  --apt-recommends false \
  --apt-source-archives false \
  --binary-image iso-hybrid \
  --bootloaders "syslinux grub-efi" \
  --bootappend-live "boot=live components username=kaadzos hostname=kaadzos quiet console=tty0 console=ttyS0,115200n8" \
  --checksums sha256 \
  --chroot-filesystem squashfs \
  --chroot-squashfs-compression-type zstd \
  --chroot-squashfs-compression-level 10 \
  --image-name kaadzos \
  --iso-application "KaadzOS" \
  --iso-publisher "KaadzOS" \
  --iso-volume "KAADZOS" \
  --memtest none \
  "${@}"
